### PR TITLE
Save scroll position for quest description and chapters

### PR DESCRIPTION
**Pull request by miozune**

### CODE REVIEW

**Comment by Steelux8** [comment]
GIF 07-02-2022 12-07-43

I ran runClient after doing a checkout on this code and made a new quest to test the scrolling (all the GTNH quests would instantly crash the game if I tried to load any of them). I scrolled down to that position, from the top, and the scrolling position was saved successfully, but any other attempts to scroll and exit would lead back to that same spot, and the last scroll position wasn't remembered anymore.

**Comment by miozune** [comment]
> all the GTNH quests would instantly crash the game if I tried to load any of them
Can you post your crashlog? I cannot reproduce the crash.

Dragging scroll bars seems to be not working in any scrolls.

**Comment by Steelux8** [comment]
<details>
  <summary>Crash log</summary>
  ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 07/02/22 11:59
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at betterquesting.client.gui2.GuiQuest.refreshTaskPanel(GuiQuest.java:359)
	at betterquesting.client.gui2.GuiQuest.initPanel(GuiQuest.java:183)
	at betterquesting.api2.client.gui.GuiScreenCanvas.initGui(GuiScreenCanvas.java:102)
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:294)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:865)
	at betterquesting.client.gui2.GuiQuestLines.onButtonPress(GuiQuestLines.java:437)
	at betterquesting.client.gui2.GuiQuestLines.onPanelEvent(GuiQuestLines.java:421)
	at betterquesting.api2.client.gui.events.PEventEntry.lambda$fire$0(PEventEntry.java:32)
	at java.util.ArrayList.forEach(Unknown Source)
	at betterquesting.api2.client.gui.events.PEventEntry.fire(PEventEntry.java:32)
	at betterquesting.api2.client.gui.events.PEventBroadcaster.postEvent(PEventBroadcaster.java:58)
	at betterquesting.api2.client.gui.controls.PanelButton.onMouseRelease(PanelButton.java:249)
	at betterquesting.api2.client.gui.panels.lists.CanvasScrolling.onMouseRelease(CanvasScrolling.java:356)
	at betterquesting.api2.client.gui.panels.CanvasResizeable.onMouseRelease(CanvasResizeable.java:145)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.onMouseRelease(CanvasEmpty.java:97)
	at betterquesting.api2.client.gui.GuiScreenCanvas.onMouseRelease(GuiScreenCanvas.java:301)
	at betterquesting.api2.client.gui.GuiScreenCanvas.handleMouseInput(GuiScreenCanvas.java:209)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:313)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1731)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1039)
	at net.minecraft.client.Minecraft.run(Minecraft.java:962)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at betterquesting.client.gui2.GuiQuest.refreshTaskPanel(GuiQuest.java:359)
	at betterquesting.client.gui2.GuiQuest.initPanel(GuiQuest.java:183)
	at betterquesting.api2.client.gui.GuiScreenCanvas.initGui(GuiScreenCanvas.java:102)
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:294)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:865)
	at betterquesting.client.gui2.GuiQuestLines.onButtonPress(GuiQuestLines.java:437)
	at betterquesting.client.gui2.GuiQuestLines.onPanelEvent(GuiQuestLines.java:421)
	at betterquesting.api2.client.gui.events.PEventEntry.lambda$fire$0(PEventEntry.java:32)
	at java.util.ArrayList.forEach(Unknown Source)
	at betterquesting.api2.client.gui.events.PEventEntry.fire(PEventEntry.java:32)
	at betterquesting.api2.client.gui.events.PEventBroadcaster.postEvent(PEventBroadcaster.java:58)
	at betterquesting.api2.client.gui.controls.PanelButton.onMouseRelease(PanelButton.java:249)
	at betterquesting.api2.client.gui.panels.lists.CanvasScrolling.onMouseRelease(CanvasScrolling.java:356)
	at betterquesting.api2.client.gui.panels.CanvasResizeable.onMouseRelease(CanvasResizeable.java:145)
	at betterquesting.api2.client.gui.panels.CanvasEmpty.onMouseRelease(CanvasEmpty.java:97)
	at betterquesting.api2.client.gui.GuiScreenCanvas.onMouseRelease(GuiScreenCanvas.java:301)
	at betterquesting.api2.client.gui.GuiScreenCanvas.handleMouseInput(GuiScreenCanvas.java:209)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:313)

-- Affected screen --
Details:
	Screen name: betterquesting.client.gui2.GuiQuest

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Developer'/207, l='MpServer', x=-1197.92, y=5.62, z=-270.79]]
	Chunk stats: MultiplayerChunkCache: 30, 30
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1200,4,-282), Chunk: (at 0,0,6 in -75,-18; contains blocks -1200,0,-288 to -1185,255,-273), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Level time: 1352 game time, 1352 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['Developer'/207, l='MpServer', x=-1197.92, y=5.62, z=-270.79]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:415)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2566)
	at net.minecraft.client.Minecraft.run(Minecraft.java:984)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 334489944 bytes (318 MB) / 551387136 bytes (525 MB) up to 6407585792 bytes (6110 MB)
	JVM Flags: 3 total; -Xincgc -Xms256M -Xmx6G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forgeSrc-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	betterquesting{3.0.352-GTNH} [BetterQuesting] (BetterQuesting-1.7.10-3.0.352-GTNH-1-g70e4181.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.5100' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.5100, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
</details>

**Comment by miozune** [comment]
Hmm, that crash could have occured before my changes... ez fix anyway.

**Comment by Steelux8** [comment]
I did not mean to imply that the crashes happened because of your changes, I assumed they were there before.

Regardless, I will test the scrolling again.

**Review by Steelux8 — APPROVED** [review]

**Pull request merged**
