### PR TITLE
Enable & run spotless

### PR DESCRIPTION
**Pull request by Lyfts**
The formatting in this mod leaves a whole lot to be desired so I think it's about time that we enable spotless. It's been ~2 years since anything was pulled in from upstream and this fork has deviated a ton during that time.

### CODE REVIEW

**Comment by wlhlm** [comment]
I think it's time 👍

**Comment by wlhlm** [comment]
OK, so this weird: I just verifying your PR by checking out the branch at commit 3cca49d4d747889f2cac53f47a2ead05f209362d, and running spotlessApply in my own devenv, but it looks like I'm getting different results from spotless. I have pushed my spotless result in the branch [spotless-test]() just in case.

Doing some spot checks, there seems to be some interesting formatting changes in your branch. For example in `src/main/java/betterquesting/api2/cache/QuestCache.java`:
https://github.com/GTNewHorizons/BetterQuesting/pull/152/commits/58c8753b38437adf2e176b1fff139f5f0d59c885#diff-87f642cbeeb792574e758592767df654ce7ba2167c1ab66d6281fd389de18455R142

Screenshot 2024-11-07 205322

Is that really how our config is set up?

Here is what the git graph looks like for reference:
Screenshot 2024-11-07 204929

**Comment by Lyfts** [comment]
I originally ran spotless with the old blowdryer tag but then updated and re-ran it, guess it just didn't feel like fixing all of that 🤷 Should be good now.

**Review by wlhlm — APPROVED** [review]
Yep, I now get the same result when running spotlessApply locally.

**Comment by wlhlm** [comment]
Please make a follow-up PR adding a `.git-blame-ignore-revs` file once this is merged.

**Pull request merged**
