### PR TITLE
Store progress for per player individually

### PR DESCRIPTION
**Pull request by MuXiu1997**
Closed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9662

Tested in SP only, seems to work properly
Not tested in server yet

Feedback welcome

### CODE REVIEW

**Comment by boubou19** [comment]
does it migrate well between the previous system and yout system?

**Comment by MuXiu1997** [comment]
> does it migrate well between the previous system and yout system?

In fact, since the author's previous interface was designed to take into account individual user loading or saving progress
so migration should be fully supported

**Comment by MuXiu1997** [comment]
The implementation of `reset [all|<quest_id>] [username|uuid]`  still needs to be modified
Other than that it should be available

**Comment by MuXiu1997** [comment]
If we mark the players whose progress has changed as dirty, wouldn't we be able to save only the progress of those players when we save?
But this needs to be modified  `ITask`
 @Glease  what do you think

**Review by Glease — COMMENTED** [review]
seems ok. not sure if there is enough markDirty though. let's wait the merging a bit until he has pushed the changes in standard expansion.

**Review by Glease — APPROVED** [review]
Actually, let's just merge this now so he can develop standard expansion easier. jitpack isn't that convenient to use

**Pull request merged**
