### PR TITLE
Update NativeProps.java

### PR DESCRIPTION
**Pull request by Pilad**
Fix sound for quests.

### CODE REVIEW

**Comment by richardhendricks** [comment]
Can you push this upstream to @funwayguy's master repo?  They have been working with us to keep BQ3 up to date on 1.7.10, so I don't think we need to start our own branch yet.

**Comment by richardhendricks** [comment]
I'll put in a ticket to update our current quest sounds to make sure we haven't missed any new quests.

**Comment by Pilad** [comment]
> 
> 
> Can you push this upstream to @Funwayguy's master repo? They have been working with us to keep BQ3 up to date on 1.7.10, so I don't think we need to start our own branch yet.

Since I made a fork of both GTNH and the official mod, when creating the PR, he tries to transfer not only my PR, but also the GTNH. Something I'm confused.

**Comment by Pilad** [comment]
Try it yourself to the author of the mod to convey the changes to the sounds. Something with the git I can’t figure out how to do.

**Comment by Dream-Master** [comment]
@richardhendricks since we maintained now us fork of BQ3 can we merge this ?

**Comment by Dream-Master** [comment]
let see if that works

**Pull request merged**
