### PR TITLE
Add Formatting Macros for Quest Descriptions

### PR DESCRIPTION
**Pull request by Steelux8**
GIF 01-12-2023 15-21-51

This PR adds new options in the text formatting of quest descriptions. Instead of using the previously added buttons to [format text with color and some extra options, as done by vanilla Minecraft text formatting rules](https://minecraft.fandom.com/wiki/Formatting_codes), these new buttons add a block of text with specific formatting, so that devs can follow a standard of formatting. [In the developer's guide for making quests](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/tree/master/config/betterquesting), there are only three colors mentioned, all of which are included here: dark red for warnings, dark aqua for "PS:" entries and default for the rest of the text. On top of that, hyperlinks are supposed to be underlined and colored dark-blue, although I set the color here to blue because it's easier to read in dark themes.

<details>
  <summary>Example of formatted text in various BQ themes</summary>
  

</details>

Note: the formatting decisions in this example are something I came up in the moment. We don't have any rules for how to format descriptions aside from the three colors. Standardizing quest formatting is a topic that can be discussed.

### CODE REVIEW

**Comment by chochem** [comment]
well since you are asking me.

the link one is nice, though the format isnt quite right.
Don't like the rest. Colors already have buttons and those themes are questionable.

well thats my take anyway.

**Comment by Prometheus0000** [comment]
Dream asked for my opinion, so here it is:

I think showing the color on the left sounds like a good idea, so you can tell what it looks like, and I assume we just don't see the non-color ones since they wanted to focus on the colors. Though I think the obfuscated one would need an example *and* the name at least. I'm not sure about putting text that is colored there (rather than just adding the color change code), aside from the url one, I'd just erase it every time pretty much. It's also unclear as to whether these have *replaced* the old stuff there, or added them at the top. I'm not sure there's room for that, but I guess there is a scrollbar. Not to mention that I just don't think we have a real standard for these things, and that kind of discussion should take place before adding these things, though steelux did mention this, so it's not like they didn't think of that.

Having a standard is good, and it being *right there*, would certainly make people more likely to follow it, though I had no idea any colors were even mentioned in the guide, though I think it wasn't really being used or looked at while I was doing quests. I'm also *really* unsure you can really get a decent number of people to have a consensus on this, as there's very few people who work on quests usually. The idea of going over all the quests to check the colors are being used right sounds like a pain, but I suppose we could rely on people reporting them not being to the standard? Or just do it when noticed? I dunno.

Also, having a *static* image of the editing screen and the shown text as well would have helped out. I keep having to wait for it to loop to look at the earlier parts.

**Comment by chochem** [comment]
if you have no plans to change existing quests then you shouldnt try to change the standards.

**Review by chochem — CHANGES_REQUESTED** [review]
there doesnt seem to be any support for this. and even steelux has no interest in applying it either.

Lets just stay with the current standards. Though we should totally add the hyperlink template (with fixed formatting) at some point.

**Comment by bombcar** [comment]
> Lets just stay with the current standards.

I think that the idea in general is good, but that it really needs support from BQ itself (so that we can do color remapping, etc, in the future).

However, implementing the ones already "agreed" on may be worthwhile (many quest editors probably haven't noticed the URL capabilities).

**Comment by Steelux8** [comment]
I made this PR specifically because I want to apply formatting like this to all the quests I made, regardless of what other people want to do with the rest of the questbook. It's been difficult to get a proper conversation going about how we should organize our formatting, when it's all but guaranteed that most people would like more formatting than simply red or aqua text at the end of the description, and the rarely-used hyperlinks.

I don't even personally agree with the current standards because the color choice isn't appropriate for dark themes. I would at least like the hyperlink color to be changed from dark-blue to blue, and I can keep only the hyperlink button I added and remove all the others.

**Comment by Steelux8** [comment]
Closing this PR since there's not much of an agreement on the formatting options, and there's a stable release coming soon. Will re-open after the stable and try to get more feedback by then.

**Comment by Steelux8** [comment]
GIF 08-02-2024 22-23-26

This is how the formatting process looks now. Instead of adding the formatting tags that Minecraft uses, and then hiding them, the new buttons add more familiar tags before and after selected text, which are then formatted according to rules set elsewhere in the code. The current questbook theme is checked when choosing which color to use, which means that readability can be ensured regardless of which theme is used, for each formatting option.

The way it is done is far from the best, and it might conflict with image rendering that I saw being worked on recently. However, I'd like to continue this formatting process and add some more color and organization to quest descriptions, especially long ones.

**Comment by Steelux8** [comment]
I will implement this and start replacing all the formatting that matches these colors with these new tags.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
