### PR TITLE
Added heads to the Hydra and body to the Naga.

### PR DESCRIPTION
**Pull request by FindMeSomeFun**
The Hydra model little bit better.
Hydra
Also [14085](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14085) can be closed with this.

### CODE REVIEW

**Comment by Connor-Colenso** [comment]
Is it possible we could do something about the rest of the body as well? Seems weird to leave it with a floating head but definitely an improvement.

**Comment by FindMeSomeFun** [comment]
Well, here [EntityTFHydra.java#L66](https://github.com/GTNewHorizons/twilightforest/blob/5d27a126c098599c47f4087690efe3c93a696651/src/main/java/twilightforest/entity/boss/EntityTFHydra.java#L66) are body parts that are rendered, but even though here [EntityTFHydra.java#L85](https://github.com/GTNewHorizons/twilightforest/blob/5d27a126c098599c47f4087690efe3c93a696651/src/main/java/twilightforest/entity/boss/EntityTFHydra.java#L85) all parts are added to the same array, the rest of the parts are not.
I am new to modded MC and rendering, so I do not grasp how it all works.
Also, there is no [EntityTFHydraNeck](https://github.com/GTNewHorizons/twilightforest/blob/master/src/main/java/twilightforest/entity/boss/EntityTFHydraNeck.java) registered as an entity, so I cannot add it to the mix.
In the NESQL Exporter I made a Hydra image like this:
Hydra
but here adding a separate entity that is not in the center of the rotation; it rotates around itself separately from the main model, so I could not add a bunch of heads to it.

I hope someone more knowledgeable will help.

**Comment by Dream-Master** [comment]
@FindMeSomeFun is it possible to let the hydra looks like ingame ?

**Comment by FindMeSomeFun** [comment]
@Dream-Master, of course it is. If it can be rendered fully in game, then the same model can be reproduced here too, but I never did anything related to rendering, so I do not know how to do that.

I was just implementing missing features into [Not Enough SQL Exporter](https://github.com/FindMeSomeFun/nesql-exporter) so that I can export mob images for [GregTech New Horizons Questbook Wiki](https://github.com/FindMeSomeFun/gtnh-questbook-wiki) and by doing that, I just try to resolve the same problems that I encounter.

I just hope someone more familiar with this problem can do it better or chip in some advice to help me do that.
For now, this is a better looking model than the old one - at least we can see its head or three because it is the Hydra after all.

**Comment by FindMeSomeFun** [comment]
Here it is, finally!
Let's choose which ones to show in the preview.

Hydra x7: Battle Final Stage
h7

Hydra x5: Battle Middle Stage
h5

Hydra x3: Battle Beginning Stage
h3

Naga like a rattlesnake - the most compact preview
n

**Comment by Dream-Master** [comment]
@FindMeSomeFun i like the 7 head Hydra. @Connor-Colenso what do you think ?

**Comment by FindMeSomeFun** [comment]
Well I created all the parts, so for me it is just putting a number of the heads in the code.
So, we will put the model that will show the new players what to expect from it. :D

Well, overnight I realized that model parts can be rotated so I am going to remodel Naga to look more round -  not so blocky.

**Comment by FindMeSomeFun** [comment]
Here is the new Naga model.
naga

For some reason body segments spawn black and get texture in less then a minute.
I do not know what is happening here, and it is happening only for Naga body segments.

**Comment by FindMeSomeFun** [comment]
Here is the new Naga model.
naga

For some reason body segments spawn black and get texture in less then a minute, and then after a few minutes goes dark again and bright again and so on.
I do not know what is happening here, and it is happening only for Naga body segments.

**Comment by FindMeSomeFun** [comment]
Thanks to @kuba6000 's:
OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, j, k);
we are finally free from day time cycle that cause brightness change on Naga's body segments.

May I also ask about Lich model mentioned here [14085](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14085).
If we skip `readFromNBT()` if NBT is empty some models will change.
I might actually make albums using NESQL Exporter before and after implemented change so we can comment on the results.
Some mob's NBT data in different quests are different just in the head or arm position or some other not relevant data.

**Comment by FindMeSomeFun** [comment]
Thanks to @eigenraven Hydra heads are no longer lagging behind.

**Review by Connor-Colenso — APPROVED** [review]

**Pull request merged**
