### PR TITLE
Add message about non-AND task logic

### PR DESCRIPTION
**Pull request by Caedis**
Noticed that for the redstone ore quest in nightlies, its not obvious that this quest uses OR logic for its tasks, and while a note could be added to the description, a way to notify the player that you dont have to do everything would be nice.

latest layout:

348643667-11bb3e04-d431-4ba3-8725-a5bc40d04a92

TODO

- [x] Update logic to not factor in optional quests?

### CODE REVIEW

**Comment by Caedis** [comment]
Welcoming any suggestions/input on how it should look

**Comment by Dream-Master** [comment]
One other idea maybe shuffle them around like the ore dicted items so people can see what they need else. 
Or put the alternative items (raw ores) near beside the first item (ore blocks) and typ an Or between  
I try to make a picture but idk how to use gimp. normaly i use Photoshop which is not on my Laptop :)

**Comment by Caedis** [comment]
@chochem other quests dont need to be adjusted. This is just an additional reminder that only 1 task needs to be done

**Comment by chochem** [comment]
then I am against this. dont push the work on other people.

**Comment by Caedis** [comment]
What work am I pushing on other people???????

Also @Dream-Master 
image

**Comment by chochem** [comment]
> What work am I pushing on other people???????

adjusting the existing quests accordingly

**Comment by Caedis** [comment]
Nothing needs to be done to any quest. This is done automatically depending on the task logic

**Comment by chochem** [comment]
yea but its already there. so then its doubled.

**Comment by Caedis** [comment]
All this is doing is making it much more obvious to the player that they only need to do 1 of the tasks

**Comment by Dream-Master** [comment]
> What work am I pushing on other people???????
> 
> Also @Dream-Master image

yes like this or if possible let the other items appear on the right side so quest looks different than normal quests.

**Review by Alastors — APPROVED** [review]
I mean personally I think this is a good addition when all of the raw ore shit is going to be a mess of confusion to players otherwise

**Comment by Caedis** [comment]
> if possible let the other items appear on the right side so quest looks different than normal quests.

Having trouble visualizing that

**Comment by Dream-Master** [comment]
@Alastors not approve stuff that is not done and draft :trollface:

**Comment by Dream-Master** [comment]
> > if possible let the other items appear on the right side so quest looks different than normal quests.
> 
> Having trouble visualizing that

because people use different Window sizes ?

**Comment by Alastors** [comment]
Shit didn't notice this was a draft, just kept getting repeatedly pinged with the quest book repo

**Comment by chochem** [comment]
maybe pictures are clearer if you are not following. This is how it works currently:

image
image

moving the info is fine, doubling it is silly.

**Comment by Caedis** [comment]
Double info for something like this is fine to drive the point home that you only need to do 1 of them.

**Comment by Lyfts** [comment]
Relying on people manually adding that info to the quest description is hardly a solution.

**Comment by chochem** [comment]
> Relying on people manually adding that info to the quest description is hardly a solution.

It literally *has been* the solution for 8 years. Anyway it just needs to be adjusted.

**Comment by Lyfts** [comment]
That doesn't make an automatic solution a bad idea though

**Comment by chochem** [comment]
nobody is saying its a bad idea.

**Comment by Alastors** [comment]
Yeah I agree, why is automation a bad thing just because it'll have some minor impacts on existing things to the point we should actively cause more work in the future adding this information to quests manually

**Comment by Caedis** [comment]
@Dream-Master needs tweaking, but what about something like this?
image

**Comment by Caedis** [comment]
and tweaked
image

different scale and theme
image
image

**Comment by Dream-Master** [comment]
> and tweaked image
> 
> different scale and theme image image

Sure that work two . Guess it’s the second best option if horizontal position not possible.

**Comment by Caedis** [comment]
Are you okay with it affecting all tasks and not just the OR task logic?

**Comment by Caedis** [comment]
Example
image

**Comment by Dream-Master** [comment]
Yes but it need to be very clear it’s an OR quest so item one and two need to be clear visualized .

**Comment by Caedis** [comment]
and I feel this accomplishes that

**Comment by Caedis** [comment]
@Alastors have at it

**Comment by chochem** [comment]
whats the design you went with now?

**Comment by Dream-Master** [comment]
image
@chochem

**Comment by Dream-Master** [comment]
image

**Comment by chochem** [comment]
ah so completely different than the description.

And why is this ready for review when there are 2 open todos?

**Comment by Caedis** [comment]
If you read the pr, you can see we did something called communication. Sometimes this can change what was discussed prior.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
